// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using projetNet.Data;

#nullable disable

namespace projetNet.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260212004327_minor fix")]
    partial class minorfix
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.23")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("varchar(255)");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("longtext");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("varchar(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("varchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex");

                    b.ToTable("AspNetRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("ClaimType")
                        .HasColumnType("longtext");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("longtext");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasColumnType("varchar(255)");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("ClaimType")
                        .HasColumnType("longtext");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("longtext");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("varchar(255)");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasMaxLength(128)
                        .HasColumnType("varchar(128)");

                    b.Property<string>("ProviderKey")
                        .HasMaxLength(128)
                        .HasColumnType("varchar(128)");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("longtext");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("varchar(255)");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("varchar(255)");

                    b.Property<string>("RoleId")
                        .HasColumnType("varchar(255)");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("varchar(255)");

                    b.Property<string>("LoginProvider")
                        .HasMaxLength(128)
                        .HasColumnType("varchar(128)");

                    b.Property<string>("Name")
                        .HasMaxLength(128)
                        .HasColumnType("varchar(128)");

                    b.Property<string>("Value")
                        .HasColumnType("longtext");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("projetNet.Models.ApplicationUser", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("varchar(255)");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("longtext");

                    b.Property<DateTime?>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("varchar(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("FirstName")
                        .HasColumnType("longtext");

                    b.Property<bool>("IsEmailVerified")
                        .HasColumnType("tinyint(1)");

                    b.Property<bool>("IsPhoneVerified")
                        .HasColumnType("tinyint(1)");

                    b.Property<bool?>("IsVerifiedSeller")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("LastName")
                        .HasColumnType("longtext");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("tinyint(1)");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("varchar(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("varchar(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("longtext");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("longtext");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("RefreshToken")
                        .HasColumnType("longtext");

                    b.Property<DateTime?>("RefreshTokenExpiryTime")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("longtext");

                    b.Property<double>("SellerRating")
                        .HasColumnType("double");

                    b.Property<int>("SellerReviewCount")
                        .HasColumnType("int");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("varchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex");

                    b.ToTable("AspNetUsers", (string)null);

                    b.HasData(
                        new
                        {
                            Id = "owner1",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "38a4c444-c8da-438d-9db2-05b31feed61a",
                            EmailConfirmed = false,
                            FirstName = "Jean",
                            IsEmailVerified = false,
                            IsPhoneVerified = false,
                            IsVerifiedSeller = true,
                            LastName = "Dupont",
                            LockoutEnabled = false,
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "6797def5-03ff-4cd0-8148-bb16b67eff13",
                            SellerRating = 0.0,
                            SellerReviewCount = 0,
                            TwoFactorEnabled = false,
                            UserName = "seller1"
                        },
                        new
                        {
                            Id = "owner2",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "9fcd7d03-886b-4eaa-95cf-d0619e9a4229",
                            EmailConfirmed = false,
                            FirstName = "Marie",
                            IsEmailVerified = false,
                            IsPhoneVerified = false,
                            IsVerifiedSeller = false,
                            LastName = "Curie",
                            LockoutEnabled = false,
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "54a0768f-3fb1-4eb7-a9df-6dbee6c595d7",
                            SellerRating = 0.0,
                            SellerReviewCount = 0,
                            TwoFactorEnabled = false,
                            UserName = "seller2"
                        },
                        new
                        {
                            Id = "owner3",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "f30366f7-4091-40bf-900f-63d3f7b277c8",
                            EmailConfirmed = false,
                            FirstName = "Ali",
                            IsEmailVerified = false,
                            IsPhoneVerified = false,
                            IsVerifiedSeller = true,
                            LastName = "Ben Salah",
                            LockoutEnabled = false,
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "3fd52767-d00c-4a94-808e-891674f39f3f",
                            SellerRating = 0.0,
                            SellerReviewCount = 0,
                            TwoFactorEnabled = false,
                            UserName = "seller3"
                        },
                        new
                        {
                            Id = "owner4",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "bba8c484-897a-4de8-b94a-9968ab5956e9",
                            EmailConfirmed = false,
                            FirstName = "Sophie",
                            IsEmailVerified = false,
                            IsPhoneVerified = false,
                            IsVerifiedSeller = true,
                            LastName = "Martin",
                            LockoutEnabled = false,
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "8c127684-5b52-441f-b05b-90a2ec14d99a",
                            SellerRating = 0.0,
                            SellerReviewCount = 0,
                            TwoFactorEnabled = false,
                            UserName = "seller4"
                        },
                        new
                        {
                            Id = "owner5",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "32022638-ce16-46f7-a2c1-180afde12d50",
                            EmailConfirmed = false,
                            FirstName = "David",
                            IsEmailVerified = false,
                            IsPhoneVerified = false,
                            IsVerifiedSeller = false,
                            LastName = "Smith",
                            LockoutEnabled = false,
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "91d2b176-a6b7-44c5-b792-9b12e710749c",
                            SellerRating = 0.0,
                            SellerReviewCount = 0,
                            TwoFactorEnabled = false,
                            UserName = "seller5"
                        },
                        new
                        {
                            Id = "owner6",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "38d15dca-d6cd-4200-87b0-61556dd2ded3",
                            EmailConfirmed = false,
                            FirstName = "Fatima",
                            IsEmailVerified = false,
                            IsPhoneVerified = false,
                            IsVerifiedSeller = true,
                            LastName = "El Amrani",
                            LockoutEnabled = false,
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "4e2cdc66-ee24-47a5-9650-5c3e9adcb32c",
                            SellerRating = 0.0,
                            SellerReviewCount = 0,
                            TwoFactorEnabled = false,
                            UserName = "seller6"
                        },
                        new
                        {
                            Id = "insp1",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "31db2769-951e-4e95-b4b4-aaa9a04a3499",
                            Email = "inspector1@projetnet.com",
                            EmailConfirmed = true,
                            FirstName = "Alice",
                            IsEmailVerified = false,
                            IsPhoneVerified = false,
                            LastName = "Inspector",
                            LockoutEnabled = false,
                            PhoneNumberConfirmed = true,
                            SecurityStamp = "2a876004-801e-4674-ab1f-9f54c2ab3070",
                            SellerRating = 0.0,
                            SellerReviewCount = 0,
                            TwoFactorEnabled = false,
                            UserName = "inspector1"
                        },
                        new
                        {
                            Id = "insp2",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "18c90bb0-a3eb-4217-ae32-a8f9980f305f",
                            Email = "inspector2@projetnet.com",
                            EmailConfirmed = true,
                            FirstName = "Bob",
                            IsEmailVerified = false,
                            IsPhoneVerified = false,
                            LastName = "Checker",
                            LockoutEnabled = false,
                            PhoneNumberConfirmed = true,
                            SecurityStamp = "5dfbee2e-7643-40f4-b008-3111751c7a94",
                            SellerRating = 0.0,
                            SellerReviewCount = 0,
                            TwoFactorEnabled = false,
                            UserName = "inspector2"
                        });
                });

            modelBuilder.Entity("projetNet.Models.Booking", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<string>("BookingType")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("BuyerId")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<DateTime>("EndDate")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime>("StartDate")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<decimal>("TotalAmount")
                        .HasColumnType("decimal(65,30)");

                    b.Property<Guid>("VehicleId")
                        .HasColumnType("char(36)");

                    b.HasKey("Id");

                    b.ToTable("Bookings");

                    b.HasData(
                        new
                        {
                            Id = new Guid("df79ff31-390f-4356-89af-0dffb79f020b"),
                            BookingType = "Rent",
                            BuyerId = "owner1",
                            EndDate = new DateTime(2026, 2, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            StartDate = new DateTime(2026, 2, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Status = "completed",
                            TotalAmount = 1200m,
                            VehicleId = new Guid("f83c19b3-3da2-430a-8368-f8cf9764bf42")
                        },
                        new
                        {
                            Id = new Guid("3452d6f7-4b5a-41c0-b628-89f5b496cc4b"),
                            BookingType = "Rent",
                            BuyerId = "owner3",
                            EndDate = new DateTime(2026, 1, 20, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            StartDate = new DateTime(2026, 1, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Status = "completed",
                            TotalAmount = 400m,
                            VehicleId = new Guid("4170d68a-6436-4746-9ed0-8f21483791a5")
                        });
                });

            modelBuilder.Entity("projetNet.Models.Inspection", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<string>("InspectorId")
                        .HasColumnType("longtext");

                    b.Property<string>("Reason")
                        .HasColumnType("longtext");

                    b.Property<Guid>("VehicleId")
                        .HasColumnType("char(36)");

                    b.HasKey("Id");

                    b.ToTable("Inspections");
                });

            modelBuilder.Entity("projetNet.Models.Offer", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(65,30)");

                    b.Property<string>("SellerId")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<Guid>("VehicleId")
                        .HasColumnType("char(36)");

                    b.HasKey("Id");

                    b.ToTable("Offers");

                    b.HasData(
                        new
                        {
                            Id = new Guid("2b388981-59bc-4f3f-b15a-0e941eafd1b4"),
                            Price = 15000m,
                            SellerId = "owner1",
                            Status = "accepted",
                            Type = "Sale",
                            VehicleId = new Guid("7e15fbcd-e082-4ed4-8e1c-e0dd5188966e")
                        },
                        new
                        {
                            Id = new Guid("13edb84b-e6c3-4c52-9e04-259ca76df09c"),
                            Price = 120m,
                            SellerId = "owner2",
                            Status = "accepted",
                            Type = "Rent",
                            VehicleId = new Guid("f83c19b3-3da2-430a-8368-f8cf9764bf42")
                        },
                        new
                        {
                            Id = new Guid("e08dbc4a-e247-4713-bbaf-b8c41d49d022"),
                            Price = 9000m,
                            SellerId = "owner3",
                            Status = "accepted",
                            Type = "Sale",
                            VehicleId = new Guid("d10e5432-6d5a-4efd-8503-9840e0bdea89")
                        },
                        new
                        {
                            Id = new Guid("a7a52cc2-d9bc-4e2b-9ff5-ce606775c5d1"),
                            Price = 80m,
                            SellerId = "owner4",
                            Status = "accepted",
                            Type = "Rent",
                            VehicleId = new Guid("4170d68a-6436-4746-9ed0-8f21483791a5")
                        },
                        new
                        {
                            Id = new Guid("7594725a-43a4-4f4c-add3-8db8880f41f0"),
                            Price = 25000m,
                            SellerId = "owner5",
                            Status = "accepted",
                            Type = "Sale",
                            VehicleId = new Guid("5508bdf0-c808-4226-b072-ed52a000dba9")
                        },
                        new
                        {
                            Id = new Guid("035a4b7e-4cff-4f02-98ec-bf8a944d17b6"),
                            Price = 100m,
                            SellerId = "owner6",
                            Status = "accepted",
                            Type = "Rent",
                            VehicleId = new Guid("f2dbb8ea-a5a2-4051-a488-fd492f32f1e1")
                        },
                        new
                        {
                            Id = new Guid("b8faf0cb-db66-4c58-9341-b7fdf9f91faa"),
                            Price = 8000m,
                            SellerId = "owner3",
                            Status = "rejected",
                            Type = "Sale",
                            VehicleId = new Guid("d10e5432-6d5a-4efd-8503-9840e0bdea89")
                        },
                        new
                        {
                            Id = new Guid("bb6b4d81-8825-45fe-84cd-ec7f99887c85"),
                            Price = 60m,
                            SellerId = "owner4",
                            Status = "pending",
                            Type = "Rent",
                            VehicleId = new Guid("4170d68a-6436-4746-9ed0-8f21483791a5")
                        });
                });

            modelBuilder.Entity("projetNet.Models.Vehicle", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<string>("Brand")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Description")
                        .HasColumnType("longtext");

                    b.Property<string>("ImageUrl")
                        .HasColumnType("longtext");

                    b.Property<string>("Location")
                        .HasColumnType("longtext");

                    b.Property<int?>("Mileage")
                        .HasColumnType("int");

                    b.Property<string>("Model")
                        .HasColumnType("longtext");

                    b.Property<string>("OwnerId")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<decimal?>("Price")
                        .HasColumnType("decimal(65,30)");

                    b.Property<decimal?>("RentalPrice")
                        .HasColumnType("decimal(65,30)");

                    b.Property<string>("Status")
                        .HasColumnType("longtext");

                    b.Property<string>("Vin")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int>("Year")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Vehicles");

                    b.HasData(
                        new
                        {
                            Id = new Guid("7e15fbcd-e082-4ed4-8e1c-e0dd5188966e"),
                            Brand = "Toyota",
                            Description = "Reliable sedan, low mileage.",
                            ImageUrl = "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRB79QACDPdJ92zwTCMS6L54zqDvL0kSLuzGw&s",
                            Location = "Paris",
                            Mileage = 12000,
                            Model = "Corolla",
                            OwnerId = "owner1",
                            Price = 15000m,
                            Vin = "VIN1234567890",
                            Year = 2022
                        },
                        new
                        {
                            Id = new Guid("f83c19b3-3da2-430a-8368-f8cf9764bf42"),
                            Brand = "BMW",
                            Description = "Luxury SUV, fully loaded.",
                            ImageUrl = "https://imgd.aeplcdn.com/664x374/n/cw/ec/152681/x5-exterior-right-front-three-quarter-6.jpeg?isig=0&q=80",
                            Location = "Lyon",
                            Mileage = 8000,
                            Model = "X5",
                            OwnerId = "owner2",
                            Price = 35000m,
                            Vin = "VIN0987654321",
                            Year = 2021
                        },
                        new
                        {
                            Id = new Guid("d10e5432-6d5a-4efd-8503-9840e0bdea89"),
                            Brand = "Renault",
                            Description = "Compact city car, economical.",
                            ImageUrl = "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQSlhWvzjZ8aRsjy-hZ-XsAyKEPtlmjTGArog&s",
                            Location = "Marseille",
                            Mileage = 20000,
                            Model = "Clio",
                            OwnerId = "owner3",
                            Price = 9000m,
                            Vin = "VIN1122334455",
                            Year = 2020
                        },
                        new
                        {
                            Id = new Guid("4170d68a-6436-4746-9ed0-8f21483791a5"),
                            Brand = "Peugeot",
                            Description = "Brand new, perfect for city driving.",
                            ImageUrl = "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQgxnw6GwppRxRnaBDZVANJS2hD3j1zdJAegw&s",
                            Location = "Nice",
                            Mileage = 500,
                            Model = "208",
                            OwnerId = "owner4",
                            Price = 12000m,
                            Vin = "VIN5566778899",
                            Year = 2023
                        },
                        new
                        {
                            Id = new Guid("5508bdf0-c808-4226-b072-ed52a000dba9"),
                            Brand = "Mercedes",
                            Description = "Elegant and comfortable, well maintained.",
                            ImageUrl = "https://parkers-images.bauersecure.com/wp-images/22257/cut-out/930x620/mercedes-c-class.jpg",
                            Location = "Bordeaux",
                            Mileage = 30000,
                            Model = "C-Class",
                            OwnerId = "owner5",
                            Price = 25000m,
                            Vin = "VIN9988776655",
                            Year = 2019
                        },
                        new
                        {
                            Id = new Guid("f2dbb8ea-a5a2-4051-a488-fd492f32f1e1"),
                            Brand = "Volkswagen",
                            Description = "Popular hatchback, great for families.",
                            ImageUrl = "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTfb3gI40_FUSJ4Zz5O-eRuj1uxuqdEMTt9ew&s",
                            Location = "Toulouse",
                            Mileage = 15000,
                            Model = "Golf",
                            OwnerId = "owner6",
                            Price = 14000m,
                            Vin = "VIN4455667788",
                            Year = 2021
                        });
                });

            modelBuilder.Entity("projetNet.Models.VehiculeSale", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<decimal>("Amount")
                        .HasColumnType("decimal(65,30)");

                    b.Property<string>("BuyerId")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<Guid>("OfferId")
                        .HasColumnType("char(36)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.ToTable("VehiculeSales");

                    b.HasData(
                        new
                        {
                            Id = new Guid("db46cb6f-c59d-420b-829b-500c9958eb48"),
                            Amount = 15000m,
                            BuyerId = "owner2",
                            OfferId = new Guid("7e15fbcd-e082-4ed4-8e1c-e0dd5188966e"),
                            Status = "completed"
                        },
                        new
                        {
                            Id = new Guid("6566b183-842c-4de1-aebd-95b675c07ea2"),
                            Amount = 9000m,
                            BuyerId = "owner4",
                            OfferId = new Guid("d10e5432-6d5a-4efd-8503-9840e0bdea89"),
                            Status = "completed"
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("projetNet.Models.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("projetNet.Models.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("projetNet.Models.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("projetNet.Models.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
