// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using projetNet.Data;

#nullable disable

namespace projetNet.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260211000631_more dummy data")]
    partial class moredummydata
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.23")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("varchar(255)");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("longtext");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("varchar(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("varchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex");

                    b.ToTable("AspNetRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("ClaimType")
                        .HasColumnType("longtext");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("longtext");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasColumnType("varchar(255)");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("ClaimType")
                        .HasColumnType("longtext");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("longtext");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("varchar(255)");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasMaxLength(128)
                        .HasColumnType("varchar(128)");

                    b.Property<string>("ProviderKey")
                        .HasMaxLength(128)
                        .HasColumnType("varchar(128)");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("longtext");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("varchar(255)");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("varchar(255)");

                    b.Property<string>("RoleId")
                        .HasColumnType("varchar(255)");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("varchar(255)");

                    b.Property<string>("LoginProvider")
                        .HasMaxLength(128)
                        .HasColumnType("varchar(128)");

                    b.Property<string>("Name")
                        .HasMaxLength(128)
                        .HasColumnType("varchar(128)");

                    b.Property<string>("Value")
                        .HasColumnType("longtext");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("projetNet.Models.ApplicationUser", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("varchar(255)");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("longtext");

                    b.Property<DateTime?>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("varchar(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("FirstName")
                        .HasColumnType("longtext");

                    b.Property<bool?>("IsVerifiedSeller")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("LastName")
                        .HasColumnType("longtext");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("tinyint(1)");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("varchar(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("varchar(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("longtext");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("longtext");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("RefreshToken")
                        .HasColumnType("longtext");

                    b.Property<DateTime?>("RefreshTokenExpiryTime")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("longtext");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("varchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex");

                    b.ToTable("AspNetUsers", (string)null);

                    b.HasData(
                        new
                        {
                            Id = "owner1",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "58fea65b-c000-43c3-9153-3e50e8807fc1",
                            EmailConfirmed = false,
                            FirstName = "Jean",
                            IsVerifiedSeller = true,
                            LastName = "Dupont",
                            LockoutEnabled = false,
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "24afc70a-aa24-427b-bd72-b4bf858e9eec",
                            TwoFactorEnabled = false,
                            UserName = "seller1"
                        },
                        new
                        {
                            Id = "owner2",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "8a35e6bf-01a3-4529-a4b8-ffa094d81b62",
                            EmailConfirmed = false,
                            FirstName = "Marie",
                            IsVerifiedSeller = false,
                            LastName = "Curie",
                            LockoutEnabled = false,
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "79d51093-e5dc-477f-91d1-17be29427410",
                            TwoFactorEnabled = false,
                            UserName = "seller2"
                        },
                        new
                        {
                            Id = "owner3",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "c66dfb1e-a1e2-4773-901d-716fa0a400ec",
                            EmailConfirmed = false,
                            FirstName = "Ali",
                            IsVerifiedSeller = true,
                            LastName = "Ben Salah",
                            LockoutEnabled = false,
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "2adf0f92-50c1-4cf5-bbdf-17b199313dec",
                            TwoFactorEnabled = false,
                            UserName = "seller3"
                        },
                        new
                        {
                            Id = "owner4",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "b10fd30b-2d92-47cd-93c9-0692a7415c4e",
                            EmailConfirmed = false,
                            FirstName = "Sophie",
                            IsVerifiedSeller = true,
                            LastName = "Martin",
                            LockoutEnabled = false,
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "c65df75a-dea5-4455-9082-b58fcc577a58",
                            TwoFactorEnabled = false,
                            UserName = "seller4"
                        },
                        new
                        {
                            Id = "owner5",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "24b4b289-1ff4-42ff-be61-c08fec25ce6f",
                            EmailConfirmed = false,
                            FirstName = "David",
                            IsVerifiedSeller = false,
                            LastName = "Smith",
                            LockoutEnabled = false,
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "7fc201a4-33eb-4f49-8603-7a6848fad102",
                            TwoFactorEnabled = false,
                            UserName = "seller5"
                        },
                        new
                        {
                            Id = "owner6",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "e18697d0-5d70-4149-b0b2-5f451550ad8a",
                            EmailConfirmed = false,
                            FirstName = "Fatima",
                            IsVerifiedSeller = true,
                            LastName = "El Amrani",
                            LockoutEnabled = false,
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "51eb85f6-cfa1-4cc8-a74a-ed3b907deab4",
                            TwoFactorEnabled = false,
                            UserName = "seller6"
                        });
                });

            modelBuilder.Entity("projetNet.Models.Booking", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<string>("BuyerId")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<DateTime>("EndDate")
                        .HasColumnType("datetime(6)");

                    b.Property<Guid>("OfferId")
                        .HasColumnType("char(36)");

                    b.Property<DateTime>("StartDate")
                        .HasColumnType("datetime(6)");

                    b.Property<decimal>("TotalAmount")
                        .HasColumnType("decimal(65,30)");

                    b.HasKey("Id");

                    b.ToTable("Bookings");
                });

            modelBuilder.Entity("projetNet.Models.Inspection", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<string>("InspectorId")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Report")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<DateTime>("ScheduledDate")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<Guid>("VehicleId")
                        .HasColumnType("char(36)");

                    b.HasKey("Id");

                    b.ToTable("Inspections");
                });

            modelBuilder.Entity("projetNet.Models.Offer", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(65,30)");

                    b.Property<string>("SellerId")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<Guid>("VehicleId")
                        .HasColumnType("char(36)");

                    b.HasKey("Id");

                    b.ToTable("Offers");

                    b.HasData(
                        new
                        {
                            Id = new Guid("0add8409-ac64-4006-bce9-99ca608e21bc"),
                            Price = 15000m,
                            SellerId = "owner1",
                            Status = "accepted",
                            Type = "Sale",
                            VehicleId = new Guid("f578e7bf-f5dd-42d9-864c-3910740f748c")
                        },
                        new
                        {
                            Id = new Guid("89ee2513-2a86-49a4-81cc-fd1c017f0b16"),
                            Price = 120m,
                            SellerId = "owner2",
                            Status = "accepted",
                            Type = "Rent",
                            VehicleId = new Guid("42a2775a-1183-40eb-be3c-bcf9e1a3d92f")
                        },
                        new
                        {
                            Id = new Guid("90c8f45a-88ff-47d2-830a-f04326366fa0"),
                            Price = 9000m,
                            SellerId = "owner3",
                            Status = "accepted",
                            Type = "Sale",
                            VehicleId = new Guid("5af98744-9ea8-4345-9439-5f6928760a11")
                        },
                        new
                        {
                            Id = new Guid("628c08fc-b61a-4c11-802e-4f0024bd86fe"),
                            Price = 80m,
                            SellerId = "owner4",
                            Status = "accepted",
                            Type = "Rent",
                            VehicleId = new Guid("0ecb6c7d-68f8-4d60-9f2c-a3224a49f982")
                        },
                        new
                        {
                            Id = new Guid("787b8343-ad4a-4818-9b24-2f17e86d3dad"),
                            Price = 25000m,
                            SellerId = "owner5",
                            Status = "accepted",
                            Type = "Sale",
                            VehicleId = new Guid("1b6d50b6-915e-4e3f-8b89-4cc975f95fea")
                        },
                        new
                        {
                            Id = new Guid("4e875721-54b0-47f0-a380-9427734e3a18"),
                            Price = 100m,
                            SellerId = "owner6",
                            Status = "accepted",
                            Type = "Rent",
                            VehicleId = new Guid("242ce266-814d-455d-85cf-d28e8e271901")
                        },
                        new
                        {
                            Id = new Guid("158be38a-3aa6-4353-9a20-3e0f0c1e1da7"),
                            Price = 8000m,
                            SellerId = "owner3",
                            Status = "rejected",
                            Type = "Sale",
                            VehicleId = new Guid("5af98744-9ea8-4345-9439-5f6928760a11")
                        },
                        new
                        {
                            Id = new Guid("f4e8c8c3-652e-4942-a293-42e148da29f5"),
                            Price = 60m,
                            SellerId = "owner4",
                            Status = "pending",
                            Type = "Rent",
                            VehicleId = new Guid("0ecb6c7d-68f8-4d60-9f2c-a3224a49f982")
                        });
                });

            modelBuilder.Entity("projetNet.Models.Vehicle", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<string>("Brand")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Description")
                        .HasColumnType("longtext");

                    b.Property<string>("ImageUrl")
                        .HasColumnType("longtext");

                    b.Property<string>("Location")
                        .HasColumnType("longtext");

                    b.Property<int?>("Mileage")
                        .HasColumnType("int");

                    b.Property<string>("Model")
                        .HasColumnType("longtext");

                    b.Property<string>("OwnerId")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<decimal?>("Price")
                        .HasColumnType("decimal(65,30)");

                    b.Property<decimal?>("RentalPrice")
                        .HasColumnType("decimal(65,30)");

                    b.Property<string>("Status")
                        .HasColumnType("longtext");

                    b.Property<string>("Vin")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int>("Year")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Vehicles");

                    b.HasData(
                        new
                        {
                            Id = new Guid("f578e7bf-f5dd-42d9-864c-3910740f748c"),
                            Brand = "Toyota",
                            Description = "Reliable sedan, low mileage.",
                            ImageUrl = "https://images.unsplash.com/photo-1511918984145-48bbd2aa2d4c?auto=format&fit=crop&w=400&q=80",
                            Location = "Paris",
                            Mileage = 12000,
                            Model = "Corolla",
                            OwnerId = "owner1",
                            Price = 15000m,
                            Vin = "VIN1234567890",
                            Year = 2022
                        },
                        new
                        {
                            Id = new Guid("42a2775a-1183-40eb-be3c-bcf9e1a3d92f"),
                            Brand = "BMW",
                            Description = "Luxury SUV, fully loaded.",
                            ImageUrl = "https://images.unsplash.com/photo-1503736334956-4c8f8e92946d?auto=format&fit=crop&w=400&q=80",
                            Location = "Lyon",
                            Mileage = 8000,
                            Model = "X5",
                            OwnerId = "owner2",
                            Price = 35000m,
                            Vin = "VIN0987654321",
                            Year = 2021
                        },
                        new
                        {
                            Id = new Guid("5af98744-9ea8-4345-9439-5f6928760a11"),
                            Brand = "Renault",
                            Description = "Compact city car, economical.",
                            ImageUrl = "https://images.unsplash.com/photo-1461632830798-3adb3034e4c8?auto=format&fit=crop&w=400&q=80",
                            Location = "Marseille",
                            Mileage = 20000,
                            Model = "Clio",
                            OwnerId = "owner3",
                            Price = 9000m,
                            Vin = "VIN1122334455",
                            Year = 2020
                        },
                        new
                        {
                            Id = new Guid("0ecb6c7d-68f8-4d60-9f2c-a3224a49f982"),
                            Brand = "Peugeot",
                            Description = "Brand new, perfect for city driving.",
                            ImageUrl = "https://images.unsplash.com/photo-1517336714731-489689fd1ca8?auto=format&fit=crop&w=400&q=80",
                            Location = "Nice",
                            Mileage = 500,
                            Model = "208",
                            OwnerId = "owner4",
                            Price = 12000m,
                            Vin = "VIN5566778899",
                            Year = 2023
                        },
                        new
                        {
                            Id = new Guid("1b6d50b6-915e-4e3f-8b89-4cc975f95fea"),
                            Brand = "Mercedes",
                            Description = "Elegant and comfortable, well maintained.",
                            ImageUrl = "https://images.unsplash.com/photo-1502877336888-7bfc88a5e4a0?auto=format&fit=crop&w=400&q=80",
                            Location = "Bordeaux",
                            Mileage = 30000,
                            Model = "C-Class",
                            OwnerId = "owner5",
                            Price = 25000m,
                            Vin = "VIN9988776655",
                            Year = 2019
                        },
                        new
                        {
                            Id = new Guid("242ce266-814d-455d-85cf-d28e8e271901"),
                            Brand = "Volkswagen",
                            Description = "Popular hatchback, great for families.",
                            ImageUrl = "https://images.unsplash.com/photo-1519643381400-7f7c7d3e0c44?auto=format&fit=crop&w=400&q=80",
                            Location = "Toulouse",
                            Mileage = 15000,
                            Model = "Golf",
                            OwnerId = "owner6",
                            Price = 14000m,
                            Vin = "VIN4455667788",
                            Year = 2021
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("projetNet.Models.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("projetNet.Models.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("projetNet.Models.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("projetNet.Models.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
