// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using projetNet.Data;

#nullable disable

namespace projetNet.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260211151223_migrationReset")]
    partial class migrationReset
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.23")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("varchar(255)");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("longtext");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("varchar(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("varchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex");

                    b.ToTable("AspNetRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("ClaimType")
                        .HasColumnType("longtext");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("longtext");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasColumnType("varchar(255)");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("ClaimType")
                        .HasColumnType("longtext");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("longtext");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("varchar(255)");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasMaxLength(128)
                        .HasColumnType("varchar(128)");

                    b.Property<string>("ProviderKey")
                        .HasMaxLength(128)
                        .HasColumnType("varchar(128)");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("longtext");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("varchar(255)");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("varchar(255)");

                    b.Property<string>("RoleId")
                        .HasColumnType("varchar(255)");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("varchar(255)");

                    b.Property<string>("LoginProvider")
                        .HasMaxLength(128)
                        .HasColumnType("varchar(128)");

                    b.Property<string>("Name")
                        .HasMaxLength(128)
                        .HasColumnType("varchar(128)");

                    b.Property<string>("Value")
                        .HasColumnType("longtext");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("projetNet.Models.ApplicationUser", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("varchar(255)");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("longtext");

                    b.Property<DateTime?>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("varchar(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("FirstName")
                        .HasColumnType("longtext");

                    b.Property<bool?>("IsVerifiedSeller")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("LastName")
                        .HasColumnType("longtext");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("tinyint(1)");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("varchar(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("varchar(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("longtext");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("longtext");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("RefreshToken")
                        .HasColumnType("longtext");

                    b.Property<DateTime?>("RefreshTokenExpiryTime")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("longtext");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("varchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex");

                    b.ToTable("AspNetUsers", (string)null);

                    b.HasData(
                        new
                        {
                            Id = "owner1",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "25b02e4b-cbc5-4e6e-ba68-7161ce8673d6",
                            EmailConfirmed = false,
                            FirstName = "Jean",
                            IsVerifiedSeller = true,
                            LastName = "Dupont",
                            LockoutEnabled = false,
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "5f6542aa-0297-45d1-945c-c3b759bcff3c",
                            TwoFactorEnabled = false,
                            UserName = "seller1"
                        },
                        new
                        {
                            Id = "owner2",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "8c8733e8-f1e8-4a97-876f-b5031dab328b",
                            EmailConfirmed = false,
                            FirstName = "Marie",
                            IsVerifiedSeller = false,
                            LastName = "Curie",
                            LockoutEnabled = false,
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "25601478-63bf-4f16-bd16-6ab796435293",
                            TwoFactorEnabled = false,
                            UserName = "seller2"
                        },
                        new
                        {
                            Id = "owner3",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "c5aead81-6cc3-45c5-926c-18504bf97268",
                            EmailConfirmed = false,
                            FirstName = "Ali",
                            IsVerifiedSeller = true,
                            LastName = "Ben Salah",
                            LockoutEnabled = false,
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "8cecd0d1-3b20-4388-9440-fc3c577d6377",
                            TwoFactorEnabled = false,
                            UserName = "seller3"
                        },
                        new
                        {
                            Id = "owner4",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "76edfa58-37fb-467d-8019-361c1ca7630a",
                            EmailConfirmed = false,
                            FirstName = "Sophie",
                            IsVerifiedSeller = true,
                            LastName = "Martin",
                            LockoutEnabled = false,
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "2ad50648-6c50-4534-a80f-d08b74dc5fda",
                            TwoFactorEnabled = false,
                            UserName = "seller4"
                        },
                        new
                        {
                            Id = "owner5",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "5b295f81-92f5-4c84-8b77-6c799268f540",
                            EmailConfirmed = false,
                            FirstName = "David",
                            IsVerifiedSeller = false,
                            LastName = "Smith",
                            LockoutEnabled = false,
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "c827dc42-3cb2-4c01-87a3-00ea666905bb",
                            TwoFactorEnabled = false,
                            UserName = "seller5"
                        },
                        new
                        {
                            Id = "owner6",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "cdf6014f-0417-4d54-8620-210831298772",
                            EmailConfirmed = false,
                            FirstName = "Fatima",
                            IsVerifiedSeller = true,
                            LastName = "El Amrani",
                            LockoutEnabled = false,
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "1578dfd3-4b55-40f9-8e7f-281fc1b881a7",
                            TwoFactorEnabled = false,
                            UserName = "seller6"
                        });
                });

            modelBuilder.Entity("projetNet.Models.Booking", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<string>("BuyerId")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<DateTime>("EndDate")
                        .HasColumnType("datetime(6)");

                    b.Property<Guid>("OfferId")
                        .HasColumnType("char(36)");

                    b.Property<DateTime>("StartDate")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<decimal>("TotalAmount")
                        .HasColumnType("decimal(65,30)");

                    b.HasKey("Id");

                    b.ToTable("Bookings");
                });

            modelBuilder.Entity("projetNet.Models.Inspection", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<string>("InspectorId")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Reason")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<Guid>("VehicleId")
                        .HasColumnType("char(36)");

                    b.HasKey("Id");

                    b.ToTable("Inspections");
                });

            modelBuilder.Entity("projetNet.Models.Offer", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(65,30)");

                    b.Property<string>("SellerId")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<Guid>("VehicleId")
                        .HasColumnType("char(36)");

                    b.HasKey("Id");

                    b.ToTable("Offers");

                    b.HasData(
                        new
                        {
                            Id = new Guid("9aa8de05-3e0d-4c40-8e34-0e82fbfcc0ef"),
                            Price = 15000m,
                            SellerId = "owner1",
                            Status = "accepted",
                            Type = "Sale",
                            VehicleId = new Guid("98de3205-3187-48d5-a003-74794b7682b3")
                        },
                        new
                        {
                            Id = new Guid("fed935cb-9ff3-461f-b068-55362e59ca2e"),
                            Price = 120m,
                            SellerId = "owner2",
                            Status = "accepted",
                            Type = "Rent",
                            VehicleId = new Guid("c9202144-1c5a-49e6-acb8-24732eb1b40b")
                        },
                        new
                        {
                            Id = new Guid("22d3473c-5b6b-4bf1-aa13-8ceb328e14a1"),
                            Price = 9000m,
                            SellerId = "owner3",
                            Status = "accepted",
                            Type = "Sale",
                            VehicleId = new Guid("5a99893b-c8cc-45c9-b0ec-2b7bbb9e7301")
                        },
                        new
                        {
                            Id = new Guid("2c1e9dba-d941-49c8-b58a-a352dd9fc5df"),
                            Price = 80m,
                            SellerId = "owner4",
                            Status = "accepted",
                            Type = "Rent",
                            VehicleId = new Guid("2e65d1c8-a7aa-49a6-ae50-908eebe4bb5b")
                        },
                        new
                        {
                            Id = new Guid("ad948948-b1c8-4210-b1a6-f96ca2219b35"),
                            Price = 25000m,
                            SellerId = "owner5",
                            Status = "accepted",
                            Type = "Sale",
                            VehicleId = new Guid("c6be851b-13d8-4f98-8da1-f2ac703cc87d")
                        },
                        new
                        {
                            Id = new Guid("cadd15ed-22c6-4112-bbb9-b314691deb42"),
                            Price = 100m,
                            SellerId = "owner6",
                            Status = "accepted",
                            Type = "Rent",
                            VehicleId = new Guid("9950a2f7-9f11-4686-9d30-8a07b01c4d2b")
                        },
                        new
                        {
                            Id = new Guid("ddec55ba-06a1-4542-a413-65d3a14d6916"),
                            Price = 8000m,
                            SellerId = "owner3",
                            Status = "rejected",
                            Type = "Sale",
                            VehicleId = new Guid("5a99893b-c8cc-45c9-b0ec-2b7bbb9e7301")
                        },
                        new
                        {
                            Id = new Guid("7772ef70-3007-40af-b135-3ad96b868ad5"),
                            Price = 60m,
                            SellerId = "owner4",
                            Status = "pending",
                            Type = "Rent",
                            VehicleId = new Guid("2e65d1c8-a7aa-49a6-ae50-908eebe4bb5b")
                        });
                });

            modelBuilder.Entity("projetNet.Models.Vehicle", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<string>("Brand")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Description")
                        .HasColumnType("longtext");

                    b.Property<string>("ImageUrl")
                        .HasColumnType("longtext");

                    b.Property<string>("Location")
                        .HasColumnType("longtext");

                    b.Property<int?>("Mileage")
                        .HasColumnType("int");

                    b.Property<string>("Model")
                        .HasColumnType("longtext");

                    b.Property<string>("OwnerId")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<decimal?>("Price")
                        .HasColumnType("decimal(65,30)");

                    b.Property<decimal?>("RentalPrice")
                        .HasColumnType("decimal(65,30)");

                    b.Property<string>("Status")
                        .HasColumnType("longtext");

                    b.Property<string>("Vin")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int>("Year")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Vehicles");

                    b.HasData(
                        new
                        {
                            Id = new Guid("98de3205-3187-48d5-a003-74794b7682b3"),
                            Brand = "Toyota",
                            Description = "Reliable sedan, low mileage.",
                            ImageUrl = "https://images.unsplash.com/photo-1511918984145-48bbd2aa2d4c?auto=format&fit=crop&w=400&q=80",
                            Location = "Paris",
                            Mileage = 12000,
                            Model = "Corolla",
                            OwnerId = "owner1",
                            Price = 15000m,
                            Vin = "VIN1234567890",
                            Year = 2022
                        },
                        new
                        {
                            Id = new Guid("c9202144-1c5a-49e6-acb8-24732eb1b40b"),
                            Brand = "BMW",
                            Description = "Luxury SUV, fully loaded.",
                            ImageUrl = "https://images.unsplash.com/photo-1503736334956-4c8f8e92946d?auto=format&fit=crop&w=400&q=80",
                            Location = "Lyon",
                            Mileage = 8000,
                            Model = "X5",
                            OwnerId = "owner2",
                            Price = 35000m,
                            Vin = "VIN0987654321",
                            Year = 2021
                        },
                        new
                        {
                            Id = new Guid("5a99893b-c8cc-45c9-b0ec-2b7bbb9e7301"),
                            Brand = "Renault",
                            Description = "Compact city car, economical.",
                            ImageUrl = "https://images.unsplash.com/photo-1461632830798-3adb3034e4c8?auto=format&fit=crop&w=400&q=80",
                            Location = "Marseille",
                            Mileage = 20000,
                            Model = "Clio",
                            OwnerId = "owner3",
                            Price = 9000m,
                            Vin = "VIN1122334455",
                            Year = 2020
                        },
                        new
                        {
                            Id = new Guid("2e65d1c8-a7aa-49a6-ae50-908eebe4bb5b"),
                            Brand = "Peugeot",
                            Description = "Brand new, perfect for city driving.",
                            ImageUrl = "https://images.unsplash.com/photo-1517336714731-489689fd1ca8?auto=format&fit=crop&w=400&q=80",
                            Location = "Nice",
                            Mileage = 500,
                            Model = "208",
                            OwnerId = "owner4",
                            Price = 12000m,
                            Vin = "VIN5566778899",
                            Year = 2023
                        },
                        new
                        {
                            Id = new Guid("c6be851b-13d8-4f98-8da1-f2ac703cc87d"),
                            Brand = "Mercedes",
                            Description = "Elegant and comfortable, well maintained.",
                            ImageUrl = "https://images.unsplash.com/photo-1502877336888-7bfc88a5e4a0?auto=format&fit=crop&w=400&q=80",
                            Location = "Bordeaux",
                            Mileage = 30000,
                            Model = "C-Class",
                            OwnerId = "owner5",
                            Price = 25000m,
                            Vin = "VIN9988776655",
                            Year = 2019
                        },
                        new
                        {
                            Id = new Guid("9950a2f7-9f11-4686-9d30-8a07b01c4d2b"),
                            Brand = "Volkswagen",
                            Description = "Popular hatchback, great for families.",
                            ImageUrl = "https://images.unsplash.com/photo-1519643381400-7f7c7d3e0c44?auto=format&fit=crop&w=400&q=80",
                            Location = "Toulouse",
                            Mileage = 15000,
                            Model = "Golf",
                            OwnerId = "owner6",
                            Price = 14000m,
                            Vin = "VIN4455667788",
                            Year = 2021
                        });
                });

            modelBuilder.Entity("projetNet.Models.VehiculeSale", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<decimal>("Amount")
                        .HasColumnType("decimal(65,30)");

                    b.Property<string>("BuyerId")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<Guid>("OfferId")
                        .HasColumnType("char(36)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.ToTable("VehiculeSales");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("projetNet.Models.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("projetNet.Models.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("projetNet.Models.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("projetNet.Models.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
