// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using projetNet.Data;

#nullable disable

namespace projetNet.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260212003505_fixed car images")]
    partial class fixedcarimages
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.23")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("varchar(255)");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("longtext");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("varchar(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("varchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex");

                    b.ToTable("AspNetRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("ClaimType")
                        .HasColumnType("longtext");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("longtext");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasColumnType("varchar(255)");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("ClaimType")
                        .HasColumnType("longtext");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("longtext");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("varchar(255)");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasMaxLength(128)
                        .HasColumnType("varchar(128)");

                    b.Property<string>("ProviderKey")
                        .HasMaxLength(128)
                        .HasColumnType("varchar(128)");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("longtext");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("varchar(255)");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("varchar(255)");

                    b.Property<string>("RoleId")
                        .HasColumnType("varchar(255)");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("varchar(255)");

                    b.Property<string>("LoginProvider")
                        .HasMaxLength(128)
                        .HasColumnType("varchar(128)");

                    b.Property<string>("Name")
                        .HasMaxLength(128)
                        .HasColumnType("varchar(128)");

                    b.Property<string>("Value")
                        .HasColumnType("longtext");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("projetNet.Models.ApplicationUser", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("varchar(255)");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("longtext");

                    b.Property<DateTime?>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("varchar(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("FirstName")
                        .HasColumnType("longtext");

                    b.Property<bool>("IsEmailVerified")
                        .HasColumnType("tinyint(1)");

                    b.Property<bool>("IsPhoneVerified")
                        .HasColumnType("tinyint(1)");

                    b.Property<bool?>("IsVerifiedSeller")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("LastName")
                        .HasColumnType("longtext");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("tinyint(1)");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("varchar(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("varchar(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("longtext");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("longtext");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("RefreshToken")
                        .HasColumnType("longtext");

                    b.Property<DateTime?>("RefreshTokenExpiryTime")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("longtext");

                    b.Property<double>("SellerRating")
                        .HasColumnType("double");

                    b.Property<int>("SellerReviewCount")
                        .HasColumnType("int");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("varchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex");

                    b.ToTable("AspNetUsers", (string)null);

                    b.HasData(
                        new
                        {
                            Id = "owner1",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "30a4d52f-e9f8-4bd0-96b3-4f244db8dac1",
                            EmailConfirmed = false,
                            FirstName = "Jean",
                            IsEmailVerified = false,
                            IsPhoneVerified = false,
                            IsVerifiedSeller = true,
                            LastName = "Dupont",
                            LockoutEnabled = false,
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "cd3db5bd-6157-422f-9c9e-77fd88143cb3",
                            SellerRating = 0.0,
                            SellerReviewCount = 0,
                            TwoFactorEnabled = false,
                            UserName = "seller1"
                        },
                        new
                        {
                            Id = "owner2",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "8ea1ce22-fb89-4fd3-97e6-a50a330a5970",
                            EmailConfirmed = false,
                            FirstName = "Marie",
                            IsEmailVerified = false,
                            IsPhoneVerified = false,
                            IsVerifiedSeller = false,
                            LastName = "Curie",
                            LockoutEnabled = false,
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "6b23347d-7e64-47c2-ab8a-3d0b27524032",
                            SellerRating = 0.0,
                            SellerReviewCount = 0,
                            TwoFactorEnabled = false,
                            UserName = "seller2"
                        },
                        new
                        {
                            Id = "owner3",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "ce0cbfa9-8486-4b50-9713-6f6acc8d7e31",
                            EmailConfirmed = false,
                            FirstName = "Ali",
                            IsEmailVerified = false,
                            IsPhoneVerified = false,
                            IsVerifiedSeller = true,
                            LastName = "Ben Salah",
                            LockoutEnabled = false,
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "8f23b546-7a22-4d6c-ad17-c3213e26a033",
                            SellerRating = 0.0,
                            SellerReviewCount = 0,
                            TwoFactorEnabled = false,
                            UserName = "seller3"
                        },
                        new
                        {
                            Id = "owner4",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "5cdfdeb2-094d-446c-a004-dc1c2f87168b",
                            EmailConfirmed = false,
                            FirstName = "Sophie",
                            IsEmailVerified = false,
                            IsPhoneVerified = false,
                            IsVerifiedSeller = true,
                            LastName = "Martin",
                            LockoutEnabled = false,
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "558a3967-66ba-4874-a238-76c4c25e9d98",
                            SellerRating = 0.0,
                            SellerReviewCount = 0,
                            TwoFactorEnabled = false,
                            UserName = "seller4"
                        },
                        new
                        {
                            Id = "owner5",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "a8cb89fb-5752-4e74-9f1b-025c7856f8f6",
                            EmailConfirmed = false,
                            FirstName = "David",
                            IsEmailVerified = false,
                            IsPhoneVerified = false,
                            IsVerifiedSeller = false,
                            LastName = "Smith",
                            LockoutEnabled = false,
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "81563a44-8133-4611-8fac-ec1d4b6743d8",
                            SellerRating = 0.0,
                            SellerReviewCount = 0,
                            TwoFactorEnabled = false,
                            UserName = "seller5"
                        },
                        new
                        {
                            Id = "owner6",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "38b9c3d4-3863-44c7-b457-7bca8050fbbe",
                            EmailConfirmed = false,
                            FirstName = "Fatima",
                            IsEmailVerified = false,
                            IsPhoneVerified = false,
                            IsVerifiedSeller = true,
                            LastName = "El Amrani",
                            LockoutEnabled = false,
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "c31a777b-1d4f-4543-86a1-849d6e807dfd",
                            SellerRating = 0.0,
                            SellerReviewCount = 0,
                            TwoFactorEnabled = false,
                            UserName = "seller6"
                        },
                        new
                        {
                            Id = "insp1",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "7d6f39c6-c646-44de-ad38-78809030bd5f",
                            Email = "inspector1@projetnet.com",
                            EmailConfirmed = true,
                            FirstName = "Alice",
                            IsEmailVerified = false,
                            IsPhoneVerified = false,
                            LastName = "Inspector",
                            LockoutEnabled = false,
                            PhoneNumberConfirmed = true,
                            SecurityStamp = "cbd82bff-07ac-4d58-8a02-b3869a23f50f",
                            SellerRating = 0.0,
                            SellerReviewCount = 0,
                            TwoFactorEnabled = false,
                            UserName = "inspector1"
                        },
                        new
                        {
                            Id = "insp2",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "288c9442-f76a-4823-b84f-ee35c1f958e1",
                            Email = "inspector2@projetnet.com",
                            EmailConfirmed = true,
                            FirstName = "Bob",
                            IsEmailVerified = false,
                            IsPhoneVerified = false,
                            LastName = "Checker",
                            LockoutEnabled = false,
                            PhoneNumberConfirmed = true,
                            SecurityStamp = "7241c118-13dd-4e36-831f-a1eeab04ebf4",
                            SellerRating = 0.0,
                            SellerReviewCount = 0,
                            TwoFactorEnabled = false,
                            UserName = "inspector2"
                        });
                });

            modelBuilder.Entity("projetNet.Models.Booking", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<string>("BookingType")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("BuyerId")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<DateTime>("EndDate")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime>("StartDate")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<decimal>("TotalAmount")
                        .HasColumnType("decimal(65,30)");

                    b.Property<Guid>("VehicleId")
                        .HasColumnType("char(36)");

                    b.HasKey("Id");

                    b.ToTable("Bookings");

                    b.HasData(
                        new
                        {
                            Id = new Guid("b50bcc74-ed17-486b-b5e4-a9bb995139b2"),
                            BookingType = "Rent",
                            BuyerId = "owner1",
                            EndDate = new DateTime(2026, 2, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            StartDate = new DateTime(2026, 2, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Status = "completed",
                            TotalAmount = 1200m,
                            VehicleId = new Guid("7d19af23-9db8-4177-a3b2-e67317bbe47c")
                        },
                        new
                        {
                            Id = new Guid("b22ff717-19e9-4424-b0c3-cb18228416fa"),
                            BookingType = "Rent",
                            BuyerId = "owner3",
                            EndDate = new DateTime(2026, 1, 20, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            StartDate = new DateTime(2026, 1, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Status = "completed",
                            TotalAmount = 400m,
                            VehicleId = new Guid("8280451e-8158-47d9-ad85-adb3811e74b3")
                        });
                });

            modelBuilder.Entity("projetNet.Models.Inspection", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<string>("InspectorId")
                        .HasColumnType("longtext");

                    b.Property<string>("Reason")
                        .HasColumnType("longtext");

                    b.Property<Guid>("VehicleId")
                        .HasColumnType("char(36)");

                    b.HasKey("Id");

                    b.ToTable("Inspections");
                });

            modelBuilder.Entity("projetNet.Models.Offer", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(65,30)");

                    b.Property<string>("SellerId")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<Guid>("VehicleId")
                        .HasColumnType("char(36)");

                    b.HasKey("Id");

                    b.ToTable("Offers");

                    b.HasData(
                        new
                        {
                            Id = new Guid("3f40dece-648d-44c0-b2a5-8559a1a53af5"),
                            Price = 15000m,
                            SellerId = "owner1",
                            Status = "accepted",
                            Type = "Sale",
                            VehicleId = new Guid("0cd98d8d-6c5f-48a9-a783-be5aa166febb")
                        },
                        new
                        {
                            Id = new Guid("4c87d046-8b47-418f-a4e9-3c75a22d8581"),
                            Price = 120m,
                            SellerId = "owner2",
                            Status = "accepted",
                            Type = "Rent",
                            VehicleId = new Guid("7d19af23-9db8-4177-a3b2-e67317bbe47c")
                        },
                        new
                        {
                            Id = new Guid("d5f49032-3f31-4239-8cb4-2547cb69b83e"),
                            Price = 9000m,
                            SellerId = "owner3",
                            Status = "accepted",
                            Type = "Sale",
                            VehicleId = new Guid("4e35aad7-34ac-402a-ae05-0754643ad474")
                        },
                        new
                        {
                            Id = new Guid("f60de35b-2151-44aa-a4ab-5334c881a714"),
                            Price = 80m,
                            SellerId = "owner4",
                            Status = "accepted",
                            Type = "Rent",
                            VehicleId = new Guid("8280451e-8158-47d9-ad85-adb3811e74b3")
                        },
                        new
                        {
                            Id = new Guid("d92fd3b2-b73d-4de1-9c8b-b503d750c48a"),
                            Price = 25000m,
                            SellerId = "owner5",
                            Status = "accepted",
                            Type = "Sale",
                            VehicleId = new Guid("b84b2e75-b933-4c52-97df-5635fdb480f1")
                        },
                        new
                        {
                            Id = new Guid("a3824726-8df6-4e5f-8a74-bc5bc5c4a3a6"),
                            Price = 100m,
                            SellerId = "owner6",
                            Status = "accepted",
                            Type = "Rent",
                            VehicleId = new Guid("d702e660-94d2-4b3b-b455-11e96b478703")
                        },
                        new
                        {
                            Id = new Guid("2200bc7c-e9b4-40e3-b158-ad8ab94f8dc4"),
                            Price = 8000m,
                            SellerId = "owner3",
                            Status = "rejected",
                            Type = "Sale",
                            VehicleId = new Guid("4e35aad7-34ac-402a-ae05-0754643ad474")
                        },
                        new
                        {
                            Id = new Guid("aef99f6b-5d01-4150-8e28-ca2f354175c6"),
                            Price = 60m,
                            SellerId = "owner4",
                            Status = "pending",
                            Type = "Rent",
                            VehicleId = new Guid("8280451e-8158-47d9-ad85-adb3811e74b3")
                        });
                });

            modelBuilder.Entity("projetNet.Models.Vehicle", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<string>("Brand")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Description")
                        .HasColumnType("longtext");

                    b.Property<string>("ImageUrl")
                        .HasColumnType("longtext");

                    b.Property<string>("Location")
                        .HasColumnType("longtext");

                    b.Property<int?>("Mileage")
                        .HasColumnType("int");

                    b.Property<string>("Model")
                        .HasColumnType("longtext");

                    b.Property<string>("OwnerId")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<decimal?>("Price")
                        .HasColumnType("decimal(65,30)");

                    b.Property<decimal?>("RentalPrice")
                        .HasColumnType("decimal(65,30)");

                    b.Property<string>("Status")
                        .HasColumnType("longtext");

                    b.Property<string>("Vin")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int>("Year")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Vehicles");

                    b.HasData(
                        new
                        {
                            Id = new Guid("0cd98d8d-6c5f-48a9-a783-be5aa166febb"),
                            Brand = "Toyota",
                            Description = "Reliable sedan, low mileage.",
                            ImageUrl = "https://upload.wikimedia.org/wikipedia/commons/9/9d/2019_Toyota_Corolla_Icon_Tech_VVT-i_HEV_CVT_1.8_Front.jpg",
                            Location = "Paris",
                            Mileage = 12000,
                            Model = "Corolla",
                            OwnerId = "owner1",
                            Price = 15000m,
                            Vin = "VIN1234567890",
                            Year = 2022
                        },
                        new
                        {
                            Id = new Guid("7d19af23-9db8-4177-a3b2-e67317bbe47c"),
                            Brand = "BMW",
                            Description = "Luxury SUV, fully loaded.",
                            ImageUrl = "https://upload.wikimedia.org/wikipedia/commons/2/2b/2019_BMW_X5_xDrive30d_M_Sport_Automatic_3.0_Front.jpg",
                            Location = "Lyon",
                            Mileage = 8000,
                            Model = "X5",
                            OwnerId = "owner2",
                            Price = 35000m,
                            Vin = "VIN0987654321",
                            Year = 2021
                        },
                        new
                        {
                            Id = new Guid("4e35aad7-34ac-402a-ae05-0754643ad474"),
                            Brand = "Renault",
                            Description = "Compact city car, economical.",
                            ImageUrl = "https://upload.wikimedia.org/wikipedia/commons/2/2e/2019_Renault_Clio_RS_Line_TCe_100_1.0_Front.jpg",
                            Location = "Marseille",
                            Mileage = 20000,
                            Model = "Clio",
                            OwnerId = "owner3",
                            Price = 9000m,
                            Vin = "VIN1122334455",
                            Year = 2020
                        },
                        new
                        {
                            Id = new Guid("8280451e-8158-47d9-ad85-adb3811e74b3"),
                            Brand = "Peugeot",
                            Description = "Brand new, perfect for city driving.",
                            ImageUrl = "https://upload.wikimedia.org/wikipedia/commons/2/2d/Peugeot_208_2019_IMG_3192.jpg",
                            Location = "Nice",
                            Mileage = 500,
                            Model = "208",
                            OwnerId = "owner4",
                            Price = 12000m,
                            Vin = "VIN5566778899",
                            Year = 2023
                        },
                        new
                        {
                            Id = new Guid("b84b2e75-b933-4c52-97df-5635fdb480f1"),
                            Brand = "Mercedes",
                            Description = "Elegant and comfortable, well maintained.",
                            ImageUrl = "https://upload.wikimedia.org/wikipedia/commons/2/2a/2018_Mercedes-Benz_C_200_Avantgarde_Automatic_2.0_Front.jpg",
                            Location = "Bordeaux",
                            Mileage = 30000,
                            Model = "C-Class",
                            OwnerId = "owner5",
                            Price = 25000m,
                            Vin = "VIN9988776655",
                            Year = 2019
                        },
                        new
                        {
                            Id = new Guid("d702e660-94d2-4b3b-b455-11e96b478703"),
                            Brand = "Volkswagen",
                            Description = "Popular hatchback, great for families.",
                            ImageUrl = "https://upload.wikimedia.org/wikipedia/commons/7/7e/2019_Volkswagen_Golf_Mk7_facelift_1.5_Front.jpg",
                            Location = "Toulouse",
                            Mileage = 15000,
                            Model = "Golf",
                            OwnerId = "owner6",
                            Price = 14000m,
                            Vin = "VIN4455667788",
                            Year = 2021
                        });
                });

            modelBuilder.Entity("projetNet.Models.VehiculeSale", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<decimal>("Amount")
                        .HasColumnType("decimal(65,30)");

                    b.Property<string>("BuyerId")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<Guid>("OfferId")
                        .HasColumnType("char(36)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.ToTable("VehiculeSales");

                    b.HasData(
                        new
                        {
                            Id = new Guid("8565d618-bd01-44ca-af17-38720ffa30e1"),
                            Amount = 15000m,
                            BuyerId = "owner2",
                            OfferId = new Guid("0cd98d8d-6c5f-48a9-a783-be5aa166febb"),
                            Status = "completed"
                        },
                        new
                        {
                            Id = new Guid("85a6e2e3-9d11-420d-8682-66027015e353"),
                            Amount = 9000m,
                            BuyerId = "owner4",
                            OfferId = new Guid("4e35aad7-34ac-402a-ae05-0754643ad474"),
                            Status = "completed"
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("projetNet.Models.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("projetNet.Models.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("projetNet.Models.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("projetNet.Models.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
