// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using projetNet.Data;

#nullable disable

namespace projetNet.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260212110121_fixingfront")]
    partial class fixingfront
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.23")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("varchar(255)");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("longtext");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("varchar(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("varchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex");

                    b.ToTable("AspNetRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("ClaimType")
                        .HasColumnType("longtext");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("longtext");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasColumnType("varchar(255)");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("ClaimType")
                        .HasColumnType("longtext");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("longtext");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("varchar(255)");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasMaxLength(128)
                        .HasColumnType("varchar(128)");

                    b.Property<string>("ProviderKey")
                        .HasMaxLength(128)
                        .HasColumnType("varchar(128)");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("longtext");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("varchar(255)");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("varchar(255)");

                    b.Property<string>("RoleId")
                        .HasColumnType("varchar(255)");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("varchar(255)");

                    b.Property<string>("LoginProvider")
                        .HasMaxLength(128)
                        .HasColumnType("varchar(128)");

                    b.Property<string>("Name")
                        .HasMaxLength(128)
                        .HasColumnType("varchar(128)");

                    b.Property<string>("Value")
                        .HasColumnType("longtext");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("projetNet.Models.ApplicationUser", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("varchar(255)");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("longtext");

                    b.Property<DateTime?>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("varchar(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("FirstName")
                        .HasColumnType("longtext");

                    b.Property<bool>("IsEmailVerified")
                        .HasColumnType("tinyint(1)");

                    b.Property<bool>("IsPhoneVerified")
                        .HasColumnType("tinyint(1)");

                    b.Property<bool?>("IsVerifiedSeller")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("LastName")
                        .HasColumnType("longtext");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("tinyint(1)");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("varchar(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("varchar(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("longtext");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("longtext");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("RefreshToken")
                        .HasColumnType("longtext");

                    b.Property<DateTime?>("RefreshTokenExpiryTime")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("longtext");

                    b.Property<double>("SellerRating")
                        .HasColumnType("double");

                    b.Property<int>("SellerReviewCount")
                        .HasColumnType("int");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("varchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex");

                    b.ToTable("AspNetUsers", (string)null);

                    b.HasData(
                        new
                        {
                            Id = "owner1",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "b5f2bbf2-2999-4311-93e1-8f771c10dd90",
                            EmailConfirmed = false,
                            FirstName = "Jean",
                            IsEmailVerified = false,
                            IsPhoneVerified = false,
                            IsVerifiedSeller = true,
                            LastName = "Dupont",
                            LockoutEnabled = false,
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "4de17271-51e4-422d-a78b-398a92f518fb",
                            SellerRating = 0.0,
                            SellerReviewCount = 0,
                            TwoFactorEnabled = false,
                            UserName = "seller1"
                        },
                        new
                        {
                            Id = "owner2",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "f8c3a9bc-01f3-4aee-8f60-2e500dbb4462",
                            EmailConfirmed = false,
                            FirstName = "Marie",
                            IsEmailVerified = false,
                            IsPhoneVerified = false,
                            IsVerifiedSeller = false,
                            LastName = "Curie",
                            LockoutEnabled = false,
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "e9a7cfeb-23fa-4694-b8b3-38c62b6f6a97",
                            SellerRating = 0.0,
                            SellerReviewCount = 0,
                            TwoFactorEnabled = false,
                            UserName = "seller2"
                        },
                        new
                        {
                            Id = "owner3",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "a9864e09-4928-48ac-83b4-dbaa7de0f86c",
                            EmailConfirmed = false,
                            FirstName = "Ali",
                            IsEmailVerified = false,
                            IsPhoneVerified = false,
                            IsVerifiedSeller = true,
                            LastName = "Ben Salah",
                            LockoutEnabled = false,
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "9fcbafce-b9bf-49d8-9856-f8b4dc13766f",
                            SellerRating = 0.0,
                            SellerReviewCount = 0,
                            TwoFactorEnabled = false,
                            UserName = "seller3"
                        },
                        new
                        {
                            Id = "owner4",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "36b8fbcf-1a61-4a3f-b602-bf0a7b3be109",
                            EmailConfirmed = false,
                            FirstName = "Sophie",
                            IsEmailVerified = false,
                            IsPhoneVerified = false,
                            IsVerifiedSeller = true,
                            LastName = "Martin",
                            LockoutEnabled = false,
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "4be5d769-eed4-45e9-9f3b-850ca9358f40",
                            SellerRating = 0.0,
                            SellerReviewCount = 0,
                            TwoFactorEnabled = false,
                            UserName = "seller4"
                        },
                        new
                        {
                            Id = "owner5",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "01cc4230-2d5b-467f-8bdf-521dba1b878a",
                            EmailConfirmed = false,
                            FirstName = "David",
                            IsEmailVerified = false,
                            IsPhoneVerified = false,
                            IsVerifiedSeller = false,
                            LastName = "Smith",
                            LockoutEnabled = false,
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "4dee556b-b39e-49d3-8fc5-0c39f0cc7a16",
                            SellerRating = 0.0,
                            SellerReviewCount = 0,
                            TwoFactorEnabled = false,
                            UserName = "seller5"
                        },
                        new
                        {
                            Id = "owner6",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "78dc4324-b0a0-4843-8d8a-0080805d053e",
                            EmailConfirmed = false,
                            FirstName = "Fatima",
                            IsEmailVerified = false,
                            IsPhoneVerified = false,
                            IsVerifiedSeller = true,
                            LastName = "El Amrani",
                            LockoutEnabled = false,
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "6e265975-700b-4d99-a69b-de34b95328e2",
                            SellerRating = 0.0,
                            SellerReviewCount = 0,
                            TwoFactorEnabled = false,
                            UserName = "seller6"
                        },
                        new
                        {
                            Id = "insp1",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "039e9159-2046-45e2-8c7d-2fd980a7c726",
                            Email = "inspector1@projetnet.com",
                            EmailConfirmed = true,
                            FirstName = "Alice",
                            IsEmailVerified = false,
                            IsPhoneVerified = false,
                            LastName = "Inspector",
                            LockoutEnabled = false,
                            PhoneNumberConfirmed = true,
                            SecurityStamp = "b5e35070-63fd-4231-9792-05a5cd136b8f",
                            SellerRating = 0.0,
                            SellerReviewCount = 0,
                            TwoFactorEnabled = false,
                            UserName = "inspector1"
                        },
                        new
                        {
                            Id = "insp2",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "aaab4f99-29f3-4ba6-8582-2ad05f851cb4",
                            Email = "inspector2@projetnet.com",
                            EmailConfirmed = true,
                            FirstName = "Bob",
                            IsEmailVerified = false,
                            IsPhoneVerified = false,
                            LastName = "Checker",
                            LockoutEnabled = false,
                            PhoneNumberConfirmed = true,
                            SecurityStamp = "95488971-af4b-403c-82e9-1bcadc542faf",
                            SellerRating = 0.0,
                            SellerReviewCount = 0,
                            TwoFactorEnabled = false,
                            UserName = "inspector2"
                        });
                });

            modelBuilder.Entity("projetNet.Models.Booking", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<string>("BookingType")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("BuyerId")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<DateTime>("EndDate")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime>("StartDate")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<decimal>("TotalAmount")
                        .HasColumnType("decimal(65,30)");

                    b.Property<Guid>("VehicleId")
                        .HasColumnType("char(36)");

                    b.HasKey("Id");

                    b.ToTable("Bookings");

                    b.HasData(
                        new
                        {
                            Id = new Guid("857aee55-96f2-448c-a11e-80dc6d884ecc"),
                            BookingType = "Rent",
                            BuyerId = "owner1",
                            EndDate = new DateTime(2026, 2, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            StartDate = new DateTime(2026, 2, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Status = "completed",
                            TotalAmount = 1200m,
                            VehicleId = new Guid("0f29ec4b-d7da-4c10-bcd3-e60b595b5d73")
                        },
                        new
                        {
                            Id = new Guid("9c2ceb4f-c370-4474-a34c-a4a609d2801c"),
                            BookingType = "Rent",
                            BuyerId = "owner3",
                            EndDate = new DateTime(2026, 1, 20, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            StartDate = new DateTime(2026, 1, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Status = "completed",
                            TotalAmount = 400m,
                            VehicleId = new Guid("b5b13b24-eb33-4326-9af0-758b430e3c90")
                        });
                });

            modelBuilder.Entity("projetNet.Models.Inspection", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<string>("InspectorId")
                        .HasColumnType("longtext");

                    b.Property<string>("Reason")
                        .HasColumnType("longtext");

                    b.Property<Guid>("VehicleId")
                        .HasColumnType("char(36)");

                    b.HasKey("Id");

                    b.ToTable("Inspections");
                });

            modelBuilder.Entity("projetNet.Models.Offer", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(65,30)");

                    b.Property<string>("SellerId")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<Guid>("VehicleId")
                        .HasColumnType("char(36)");

                    b.HasKey("Id");

                    b.ToTable("Offers");

                    b.HasData(
                        new
                        {
                            Id = new Guid("8502e524-23b5-46c8-8414-aff9ed8af851"),
                            Price = 15000m,
                            SellerId = "owner1",
                            Status = "accepted",
                            Type = "Sale",
                            VehicleId = new Guid("ae108f8e-a7b2-422a-9b04-ce2b86087ef3")
                        },
                        new
                        {
                            Id = new Guid("0c557ce1-6b9b-4b6e-95e7-ba31019f52ad"),
                            Price = 120m,
                            SellerId = "owner2",
                            Status = "accepted",
                            Type = "Rent",
                            VehicleId = new Guid("0f29ec4b-d7da-4c10-bcd3-e60b595b5d73")
                        },
                        new
                        {
                            Id = new Guid("ab0f3b4f-adb2-4de7-b2f7-4910335cbc34"),
                            Price = 9000m,
                            SellerId = "owner3",
                            Status = "accepted",
                            Type = "Sale",
                            VehicleId = new Guid("060020f8-9afe-49ff-9b20-a9db564497ab")
                        },
                        new
                        {
                            Id = new Guid("0d45e41e-f0bd-4f62-99b0-87f1d9691bf8"),
                            Price = 80m,
                            SellerId = "owner4",
                            Status = "accepted",
                            Type = "Rent",
                            VehicleId = new Guid("b5b13b24-eb33-4326-9af0-758b430e3c90")
                        },
                        new
                        {
                            Id = new Guid("356964dd-edaa-46c7-84a1-4c1b6eb56394"),
                            Price = 25000m,
                            SellerId = "owner5",
                            Status = "accepted",
                            Type = "Sale",
                            VehicleId = new Guid("08b72382-73d1-44ea-8538-408bfc37e19b")
                        },
                        new
                        {
                            Id = new Guid("2fd7ae14-63fa-4ec7-9626-8c4b545eea65"),
                            Price = 100m,
                            SellerId = "owner6",
                            Status = "accepted",
                            Type = "Rent",
                            VehicleId = new Guid("ca4aa63e-b63c-473b-bcd1-59b2e7fed473")
                        },
                        new
                        {
                            Id = new Guid("02e1547f-d0c4-4827-a4e4-45d76dd4ff96"),
                            Price = 8000m,
                            SellerId = "owner3",
                            Status = "rejected",
                            Type = "Sale",
                            VehicleId = new Guid("060020f8-9afe-49ff-9b20-a9db564497ab")
                        },
                        new
                        {
                            Id = new Guid("4c45d229-b775-4f13-b140-ba5ab23010ab"),
                            Price = 60m,
                            SellerId = "owner4",
                            Status = "pending",
                            Type = "Rent",
                            VehicleId = new Guid("b5b13b24-eb33-4326-9af0-758b430e3c90")
                        });
                });

            modelBuilder.Entity("projetNet.Models.Vehicle", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<string>("Brand")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Description")
                        .HasColumnType("longtext");

                    b.Property<string>("ImageUrl")
                        .HasColumnType("longtext");

                    b.Property<string>("Location")
                        .HasColumnType("longtext");

                    b.Property<int?>("Mileage")
                        .HasColumnType("int");

                    b.Property<string>("Model")
                        .HasColumnType("longtext");

                    b.Property<string>("OwnerId")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<decimal?>("Price")
                        .HasColumnType("decimal(65,30)");

                    b.Property<decimal?>("RentalPrice")
                        .HasColumnType("decimal(65,30)");

                    b.Property<string>("Status")
                        .HasColumnType("longtext");

                    b.Property<string>("Vin")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int>("Year")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Vehicles");

                    b.HasData(
                        new
                        {
                            Id = new Guid("ae108f8e-a7b2-422a-9b04-ce2b86087ef3"),
                            Brand = "Toyota",
                            Description = "Reliable sedan, low mileage.",
                            ImageUrl = "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRB79QACDPdJ92zwTCMS6L54zqDvL0kSLuzGw&s",
                            Location = "Paris",
                            Mileage = 12000,
                            Model = "Corolla",
                            OwnerId = "owner1",
                            Price = 15000m,
                            Vin = "VIN1234567890",
                            Year = 2022
                        },
                        new
                        {
                            Id = new Guid("0f29ec4b-d7da-4c10-bcd3-e60b595b5d73"),
                            Brand = "BMW",
                            Description = "Luxury SUV, fully loaded.",
                            ImageUrl = "https://imgd.aeplcdn.com/664x374/n/cw/ec/152681/x5-exterior-right-front-three-quarter-6.jpeg?isig=0&q=80",
                            Location = "Lyon",
                            Mileage = 8000,
                            Model = "X5",
                            OwnerId = "owner2",
                            Price = 35000m,
                            Vin = "VIN0987654321",
                            Year = 2021
                        },
                        new
                        {
                            Id = new Guid("060020f8-9afe-49ff-9b20-a9db564497ab"),
                            Brand = "Renault",
                            Description = "Compact city car, economical.",
                            ImageUrl = "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQSlhWvzjZ8aRsjy-hZ-XsAyKEPtlmjTGArog&s",
                            Location = "Marseille",
                            Mileage = 20000,
                            Model = "Clio",
                            OwnerId = "owner3",
                            Price = 9000m,
                            Vin = "VIN1122334455",
                            Year = 2020
                        },
                        new
                        {
                            Id = new Guid("b5b13b24-eb33-4326-9af0-758b430e3c90"),
                            Brand = "Peugeot",
                            Description = "Brand new, perfect for city driving.",
                            ImageUrl = "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQgxnw6GwppRxRnaBDZVANJS2hD3j1zdJAegw&s",
                            Location = "Nice",
                            Mileage = 500,
                            Model = "208",
                            OwnerId = "owner4",
                            Price = 12000m,
                            Vin = "VIN5566778899",
                            Year = 2023
                        },
                        new
                        {
                            Id = new Guid("08b72382-73d1-44ea-8538-408bfc37e19b"),
                            Brand = "Mercedes",
                            Description = "Elegant and comfortable, well maintained.",
                            ImageUrl = "https://parkers-images.bauersecure.com/wp-images/22257/cut-out/930x620/mercedes-c-class.jpg",
                            Location = "Bordeaux",
                            Mileage = 30000,
                            Model = "C-Class",
                            OwnerId = "owner5",
                            Price = 25000m,
                            Vin = "VIN9988776655",
                            Year = 2019
                        },
                        new
                        {
                            Id = new Guid("ca4aa63e-b63c-473b-bcd1-59b2e7fed473"),
                            Brand = "Volkswagen",
                            Description = "Popular hatchback, great for families.",
                            ImageUrl = "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTfb3gI40_FUSJ4Zz5O-eRuj1uxuqdEMTt9ew&s",
                            Location = "Toulouse",
                            Mileage = 15000,
                            Model = "Golf",
                            OwnerId = "owner6",
                            Price = 14000m,
                            Vin = "VIN4455667788",
                            Year = 2021
                        });
                });

            modelBuilder.Entity("projetNet.Models.VehiculeSale", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<decimal>("Amount")
                        .HasColumnType("decimal(65,30)");

                    b.Property<string>("BuyerId")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<Guid>("OfferId")
                        .HasColumnType("char(36)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.ToTable("VehiculeSales");

                    b.HasData(
                        new
                        {
                            Id = new Guid("97231f53-f03f-4f85-878c-24cb030b4a8c"),
                            Amount = 15000m,
                            BuyerId = "owner2",
                            OfferId = new Guid("ae108f8e-a7b2-422a-9b04-ce2b86087ef3"),
                            Status = "completed"
                        },
                        new
                        {
                            Id = new Guid("a5977d91-f5c3-4c21-a794-15d3948226c2"),
                            Amount = 9000m,
                            BuyerId = "owner4",
                            OfferId = new Guid("060020f8-9afe-49ff-9b20-a9db564497ab"),
                            Status = "completed"
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("projetNet.Models.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("projetNet.Models.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("projetNet.Models.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("projetNet.Models.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
